
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/cmake/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:5 (project)"
    message: |
      The system is: Windows - 10.0.26220 - AMD64
...
